Fix parameter type
yiisoft/var-dumper pull request #74
Opened 2022-10-16 21:15 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

2022-10-17 09:27 UTC, arogachev requested changes
A test is needed.

2022-10-17 21:53 UTC, samdark commented on src/VarDumper.php
> +    private function getPropertyName(string|int $property): string
Are there int property names?

2022-10-19 22:31 UTC, xepozz commented on src/VarDumper.php
> +    private function getPropertyName(string|int $property): string
https://3v4l.org/3X8in

2022-10-20 05:55 UTC, vjik requested changes
1) Need changelog

2) Mutation tests is fail

2022-10-20 07:14 UTC, merged

2022-10-20 07:22 UTC, arogachev commented
Added missing changelog entry. As for mutation tests fail, it's irrelevant to this PR's changes. Now they pass on both new commit and after merge.